name: Download File

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  downloader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download the file
        run: |
          wget "https://swcdn.apple.com/content/downloads/40/56/122-28067-A_9B4FJ1TL06/zchwyidn8ubxkpelhytzb05o418bchr2se/InstallAssistant.pkg" -O downloaded.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Download-file
          path: downloaded.bin
